import type { Cluster } from "@/lib/cluster.functions";
import { toJpeg } from "html-to-image";
import { jsPDF } from "jspdf";
import { createRoot } from "react-dom/client";
import { ClusterReport } from "@/components/ClusterReport";
import { createElement } from "react";

const A4_W_MM = 210;
const A4_H_MM = 297;
const MARGIN_MM = 14;
const CONTENT_W_MM = A4_W_MM - MARGIN_MM * 2;
const CONTENT_H_MM = A4_H_MM - MARGIN_MM * 2;
const GAP_MM = 4;
const PAPER = "#f1ede3";
const PAPER_RGB: [number, number, number] = [241, 237, 227];

function slug(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "cluster";
}

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function clusterToMarkdown(cluster: Cluster): string {
  const lines: string[] = [];
  lines.push(`# Content Cluster Strategy: ${cluster.primaryTopic}`);
  lines.push("");
  lines.push(`_Generated by Cluster Cartographer on ${new Date().toLocaleDateString()}_`);
  lines.push("");
  lines.push("## Table of Contents");
  cluster.pillars.forEach((p, i) => lines.push(`${i + 1}. ${p.title}`));
  lines.push("");
  lines.push("---");
  lines.push("");
  cluster.pillars.forEach((p, i) => {
    lines.push(`## ${i + 1}. ${p.title}`);
    lines.push("");
    lines.push(p.description);
    lines.push("");
    lines.push("### Article Ideas");
    p.articles.forEach((a) => lines.push(`- ${a}`));
    lines.push("");
    lines.push("### Recommended Keywords");
    lines.push(p.keywords.map((k) => `\`${k}\``).join(", "));
    lines.push("");
    lines.push("### Internal Linking Strategy");
    p.internalLinks.forEach((l) => lines.push(`- ${l}`));
    lines.push("");
    lines.push("---");
    lines.push("");
  });
  return lines.join("\n");
}

export function exportMarkdown(cluster: Cluster) {
  download(
    new Blob([clusterToMarkdown(cluster)], { type: "text/markdown;charset=utf-8" }),
    `${slug(cluster.primaryTopic)}-strategy.md`,
  );
}

async function captureJpeg(el: HTMLElement) {
  return toJpeg(el, {
    quality: 0.95,
    pixelRatio: 2,
    backgroundColor: PAPER,
    cacheBust: true,
  });
}

function probe(dataUrl: string) {
  return new Promise<HTMLImageElement>((res, rej) => {
    const img = new Image();
    img.onload = () => res(img);
    img.onerror = rej;
    img.src = dataUrl;
  });
}

async function renderOffscreen(
  cluster: Cluster,
  logoDataUrl?: string | null,
): Promise<{ node: HTMLElement; cleanup: () => void }> {
  const host = document.createElement("div");
  host.style.position = "fixed";
  host.style.left = "-10000px";
  host.style.top = "0";
  host.style.width = "794px";
  host.style.background = PAPER;
  host.style.pointerEvents = "none";
  document.body.appendChild(host);

  const root = createRoot(host);
  root.render(createElement(ClusterReport, { cluster, logoDataUrl }));

  // Wait for fonts + a paint
  if (document.fonts && document.fonts.ready) {
    await document.fonts.ready;
  }
  await new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r)));

  const node = host.firstElementChild as HTMLElement;
  return {
    node,
    cleanup: () => {
      root.unmount();
      host.remove();
    },
  };
}

export async function exportPDF(cluster: Cluster, logoDataUrl?: string | null) {
  const { node, cleanup } = await renderOffscreen(cluster, logoDataUrl);

  try {
    const sections = Array.from(node.querySelectorAll<HTMLElement>("[data-pdf-section]"));
    const targets = sections.length > 0 ? sections : [node];

    const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    let cursorY = MARGIN_MM;
    let isFirst = true;

    for (const section of targets) {
      const dataUrl = await captureJpeg(section);
      const img = await probe(dataUrl);

      const widthMm = CONTENT_W_MM;
      const heightMm = (img.naturalHeight / img.naturalWidth) * widthMm;
      const remaining = A4_H_MM - MARGIN_MM - cursorY;

      if (heightMm <= CONTENT_H_MM) {
        if (heightMm > remaining && !isFirst) {
          pdf.addPage();
          cursorY = MARGIN_MM;
        }
        pdf.addImage(dataUrl, "JPEG", MARGIN_MM, cursorY, widthMm, heightMm);
        cursorY += heightMm + GAP_MM;
        isFirst = false;
        continue;
      }

      // Section taller than a page — slice across pages with paper masks.
      if (!isFirst) {
        pdf.addPage();
        cursorY = MARGIN_MM;
      }
      let drawn = 0;
      while (drawn < heightMm) {
        const slice = Math.min(CONTENT_H_MM, heightMm - drawn);
        pdf.addImage(dataUrl, "JPEG", MARGIN_MM, MARGIN_MM - drawn, widthMm, heightMm);
        pdf.setFillColor(...PAPER_RGB);
        pdf.rect(0, 0, A4_W_MM, MARGIN_MM, "F");
        pdf.rect(0, MARGIN_MM + slice, A4_W_MM, A4_H_MM, "F");
        drawn += slice;
        if (drawn < heightMm) pdf.addPage();
      }
      cursorY =
        MARGIN_MM +
        (heightMm - (Math.ceil(heightMm / CONTENT_H_MM) - 1) * CONTENT_H_MM) +
        GAP_MM;
      isFirst = false;
    }

    // Page numbers
    const total = pdf.getNumberOfPages();
    for (let i = 1; i <= total; i++) {
      pdf.setPage(i);
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(8);
      pdf.setTextColor(138, 127, 114);
      pdf.text(
        `${cluster.primaryTopic}  ·  ${String(i).padStart(2, "0")} / ${String(total).padStart(2, "0")}`,
        MARGIN_MM,
        A4_H_MM - 6,
      );
    }

    pdf.save(`${slug(cluster.primaryTopic)}-strategy.pdf`);
  } finally {
    cleanup();
  }
}
