import type { Cluster } from "@/lib/cluster.functions";
import jsPDF from "jspdf";

function slug(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "cluster";
}

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function clusterToMarkdown(cluster: Cluster): string {
  const lines: string[] = [];
  lines.push(`# Content Cluster Strategy: ${cluster.primaryTopic}`);
  lines.push("");
  lines.push(`_Generated by Cluster Cartographer on ${new Date().toLocaleDateString()}_`);
  lines.push("");
  lines.push(`**Primary Topic:** ${cluster.primaryTopic}`);
  lines.push(`**Pillars:** ${cluster.pillars.length}`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Table of Contents");
  cluster.pillars.forEach((p, i) => {
    lines.push(`${i + 1}. [${p.title}](#${slug(p.title)})`);
  });
  lines.push("");
  lines.push("---");
  lines.push("");

  cluster.pillars.forEach((p, i) => {
    lines.push(`## ${i + 1}. ${p.title}`);
    lines.push("");
    lines.push(p.description);
    lines.push("");

    lines.push("### Article Ideas");
    p.articles.forEach((a) => lines.push(`- ${a}`));
    lines.push("");

    lines.push("### Recommended Keywords");
    lines.push(p.keywords.map((k) => `\`${k}\``).join(", "));
    lines.push("");

    lines.push("### Internal Linking Strategy");
    p.internalLinks.forEach((l) => lines.push(`- ${l}`));
    lines.push("");
    lines.push("---");
    lines.push("");
  });

  return lines.join("\n");
}

export function exportMarkdown(cluster: Cluster) {
  const md = clusterToMarkdown(cluster);
  download(new Blob([md], { type: "text/markdown;charset=utf-8" }), `${slug(cluster.primaryTopic)}-strategy.md`);
}

export function exportPDF(cluster: Cluster) {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 54;
  const maxW = pageW - margin * 2;
  let y = margin;

  const ensure = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const write = (text: string, opts: { size?: number; bold?: boolean; color?: [number, number, number]; gap?: number; indent?: number } = {}) => {
    const { size = 11, bold = false, color = [30, 30, 30], gap = 4, indent = 0 } = opts;
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, maxW - indent) as string[];
    const lh = size * 1.35;
    lines.forEach((line) => {
      ensure(lh);
      doc.text(line, margin + indent, y);
      y += lh;
    });
    y += gap;
  };

  const rule = () => {
    ensure(12);
    doc.setDrawColor(220);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageW - margin, y);
    y += 14;
  };

  // Cover / header
  write("CONTENT CLUSTER STRATEGY", { size: 9, bold: true, color: [120, 120, 120], gap: 6 });
  write(cluster.primaryTopic, { size: 24, bold: true, color: [20, 20, 20], gap: 8 });
  write(`Generated ${new Date().toLocaleDateString()} · ${cluster.pillars.length} pillars`, {
    size: 10,
    color: [120, 120, 120],
    gap: 10,
  });
  rule();

  // TOC
  write("Contents", { size: 14, bold: true, gap: 6 });
  cluster.pillars.forEach((p, i) => {
    write(`${i + 1}. ${p.title}`, { size: 11, color: [60, 60, 60], gap: 2, indent: 12 });
  });
  y += 10;
  rule();

  // Pillars
  cluster.pillars.forEach((p, i) => {
    ensure(80);
    write(`Pillar ${i + 1}`, { size: 9, bold: true, color: [120, 120, 120], gap: 4 });
    write(p.title, { size: 18, bold: true, color: [20, 20, 20], gap: 6 });
    write(p.description, { size: 11, color: [50, 50, 50], gap: 12 });

    write("Article Ideas", { size: 12, bold: true, color: [30, 30, 30], gap: 6 });
    p.articles.forEach((a) => write(`•  ${a}`, { size: 11, color: [50, 50, 50], gap: 2, indent: 8 }));
    y += 6;

    write("Recommended Keywords", { size: 12, bold: true, color: [30, 30, 30], gap: 6 });
    write(p.keywords.join("  ·  "), { size: 10, color: [70, 70, 70], gap: 10, indent: 8 });

    write("Internal Linking Strategy", { size: 12, bold: true, color: [30, 30, 30], gap: 6 });
    p.internalLinks.forEach((l) => write(`→  ${l}`, { size: 11, color: [50, 50, 50], gap: 2, indent: 8 }));

    y += 10;
    if (i < cluster.pillars.length - 1) rule();
  });

  // Footer page numbers
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(`${cluster.primaryTopic}  ·  Page ${i} of ${total}`, margin, pageH - 24);
  }

  doc.save(`${slug(cluster.primaryTopic)}-strategy.pdf`);
}
